### ISSUE TITLE
Installing seb-openedx in Juniper native

### ISSUE THREAD

**Issue by nimalr** [eduNEXT/seb-openedx#44]
Hi,

Tried installing seb-openedx in a Juniper native installation. After installation LMS reports "Internal Server Error".
The LMS log file shows the following:

>   File "/edx/app/edxapp/venvs/edxapp/lib/python3.5/site-packages/seb_openedx/urls.py", line 9, in <module>
    url(r'^dashboard/', include('seb_openedx.dashboard.urls', namespace='seb-dashboard')),
>  File "/edx/app/edxapp/venvs/edxapp/lib/python3.5/site-packages/django/urls/conf.py", line 39, in include
    'Specifying a namespace in include() without providing an app_name '
>django.core.exceptions.ImproperlyConfigured: Specifying a namespace in include() without providing an app_name is not supported. Set the app_name attribute in the included module, or pass a 2-tuple containing the list of patterns and app_name instead.

Django version installed within the venv is 

> djangorestframework==3.9.4
> djangorestframework-xml==2.0.0

Has anyone else experienced this issue?

**Comment by luismorenolopera** [comment]
Hello @nimalr can you try adding these changes? #35

**Comment by nimalr** [comment]
Thanks @luismorenolopera 
 
Installing that branch got rid of the above error, but LMS still gave "Internal Server Error".
LMS log file showed that the module rest_framework_oauth was missing.
After installing djangorestframework-oauth, LMS works again, and
https://<domain>/seb-openedx/seb-info shows the information.

**Comment by luismorenolopera** [comment]
@nimalr Excellent!
